/*-------------------------------------------------------------------------
 *
 * mys_keywords.h
 *    Declarations for the MySQL keyword list.
 *
 * The keyword list (MysScanKeywords) is generated by gen_keywordlist.pl
 * from mys_kwlist.h.  Each keyword maps to a bison token number defined
 * in the generated mys_gram.h.
 *
 * Portions Copyright (c) 2026, HaloLab / openHalo Contributors
 *
 * src/include/parser/mysql/mys_keywords.h
 *
 *-------------------------------------------------------------------------
 */
#ifndef MYS_KEYWORDS_H
#define MYS_KEYWORDS_H

#include "common/kwlookup.h"

#ifndef FRONTEND
extern PGDLLIMPORT const ScanKeywordList MysScanKeywords;
extern PGDLLIMPORT const uint8 MysScanKeywordCategories[];
#else
extern const ScanKeywordList MysScanKeywords;
extern const uint8 MysScanKeywordCategories[];
#endif

#endif							/* MYS_KEYWORDS_H */
