mysm_sources = files(
  'strfuncs.c',
  'user_var.c',  
  'aggregates.c',
  'uuid_short.c',
  'user.c',
  'operators.c',
  'partListColumns.c',
  'bpchar_pg18.c',
  'timestamp_func.c',
  'time_func.c',
  'date_func.c',
  'common_funcs.c',
  'systemVar.c',
  'texteq_mys.c',
  'mysm_globals.c',
  'uuid_stubs.c',
  'mysm_stubs.c',
  'mys_adtext.c',
  'mys_date.c',
  'mys_json.c',
  'mys_timestamp.c',
)
mysm = shared_module('mysm',
  mysm_sources,
  include_directories: postgres_inc,
  c_args: ['-fvisibility=default'],
  install: true,
  install_dir: dir_lib_pkg,
  name_prefix: '',
)
