/*-------------------------------------------------------------------------
 *
 * mys_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef MYS_KWLIST_D_H
#define MYS_KWLIST_D_H

#include "common/kwlookup.h"

static const char MysScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"any_value\0"
	"array\0"
	"as\0"
	"asc\0"
	"ascii\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"auto_increment\0"
	"avg_row_length\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"bit\0"
	"bit_as_bytea\0"
	"blob\0"
	"bool\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"charset\0"
	"check\0"
	"checkpoint\0"
	"checksum\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_format\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compression\0"
	"concurrently\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"contains\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"convert\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"databases\0"
	"date\0"
	"datetime\0"
	"day\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delay_key_write\0"
	"delayed\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"describe\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disk\0"
	"distinct\0"
	"distinctrow\0"
	"div\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"duplicate\0"
	"dynamic\0"
	"each\0"
	"else\0"
	"elseif\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"encryption\0"
	"end\0"
	"engine\0"
	"engines\0"
	"enum\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"exit\0"
	"explain\0"
	"expression\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"fields\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"forward\0"
	"found\0"
	"freeze\0"
	"from\0"
	"full\0"
	"fulltext\0"
	"function\0"
	"functions\0"
	"generated\0"
	"get\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"group_concat\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"high_priority\0"
	"hold\0"
	"hour\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"index\0"
	"indexes\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"inplace\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"insert_method\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"is\0"
	"isolation\0"
	"iterate\0"
	"join\0"
	"key\0"
	"key_block_size\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"leave\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"linear\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"longblob\0"
	"longtext\0"
	"loop\0"
	"low_priority\0"
	"mapping\0"
	"match\0"
	"materialized\0"
	"max_rows\0"
	"maxvalue\0"
	"mediumblob\0"
	"mediumint\0"
	"mediumtext\0"
	"memory\0"
	"merge\0"
	"method\0"
	"mid\0"
	"min_rows\0"
	"minute\0"
	"minvalue\0"
	"mod\0"
	"mode\0"
	"modifies\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"none\0"
	"normalize\0"
	"normalized\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"now\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"numeric\0"
	"nvarchar\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"on\0"
	"only\0"
	"open\0"
	"operator\0"
	"optimize\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"pack_keys\0"
	"parallel\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"placing\0"
	"plans\0"
	"plugins\0"
	"policy\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"processlist\0"
	"program\0"
	"publication\0"
	"quick\0"
	"quote\0"
	"range\0"
	"read\0"
	"reads\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"regexp\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"rename\0"
	"repair\0"
	"repeat\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returning\0"
	"returns\0"
	"revoke\0"
	"right\0"
	"rlike\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"row_format\0"
	"rows\0"
	"rule\0"
	"savepoint\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"seletc\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"shared\0"
	"show\0"
	"signed\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"spatial\0"
	"sql\0"
	"sql_big_result\0"
	"sql_buffer_result\0"
	"sql_cache\0"
	"sql_calc_found_rows\0"
	"sql_no_cache\0"
	"sql_small_result\0"
	"sqlexception\0"
	"sqlstate\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stats_auto_recalc\0"
	"stats_persistent\0"
	"stats_sample_pages\0"
	"status\0"
	"std\0"
	"stddev\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"strip\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substr\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"temptable\0"
	"text\0"
	"than\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"timestampadd\0"
	"timestampdiff\0"
	"tinyblob\0"
	"tinyint\0"
	"tinytext\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"triggers\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"undefined\0"
	"unencrypted\0"
	"unicode\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"unsigned\0"
	"until\0"
	"update\0"
	"use\0"
	"user\0"
	"using\0"
	"utc_date\0"
	"utc_time\0"
	"utc_timestamp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varbinary\0"
	"varchar\0"
	"variables\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"virtual\0"
	"visible\0"
	"volatile\0"
	"warnings\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"xor\0"
	"year\0"
	"yes\0"
	"zerofill\0"
	"zone";

static const uint16 MysScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	29,
	33,
	39,
	45,
	55,
	65,
	69,
	74,
	80,
	87,
	95,
	103,
	107,
	111,
	121,
	127,
	130,
	134,
	140,
	151,
	161,
	172,
	183,
	186,
	193,
	200,
	210,
	225,
	240,
	249,
	256,
	262,
	270,
	277,
	284,
	288,
	301,
	306,
	311,
	319,
	324,
	332,
	335,
	340,
	346,
	351,
	358,
	366,
	375,
	380,
	385,
	393,
	399,
	406,
	411,
	421,
	437,
	445,
	451,
	462,
	471,
	477,
	483,
	491,
	500,
	508,
	518,
	525,
	539,
	547,
	555,
	564,
	571,
	581,
	593,
	606,
	620,
	629,
	640,
	651,
	663,
	672,
	680,
	689,
	700,
	708,
	713,
	718,
	725,
	731,
	735,
	740,
	748,
	764,
	777,
	790,
	805,
	818,
	836,
	849,
	856,
	862,
	867,
	876,
	886,
	891,
	900,
	904,
	915,
	919,
	927,
	935,
	943,
	952,
	963,
	972,
	980,
	996,
	1004,
	1011,
	1021,
	1032,
	1040,
	1046,
	1051,
	1060,
	1067,
	1081,
	1092,
	1102,
	1110,
	1118,
	1123,
	1132,
	1144,
	1148,
	1151,
	1160,
	1167,
	1174,
	1179,
	1189,
	1197,
	1202,
	1207,
	1214,
	1221,
	1230,
	1240,
	1251,
	1255,
	1262,
	1270,
	1275,
	1282,
	1288,
	1295,
	1303,
	1313,
	1323,
	1331,
	1338,
	1343,
	1351,
	1362,
	1372,
	1381,
	1389,
	1395,
	1402,
	1408,
	1415,
	1422,
	1431,
	1437,
	1443,
	1449,
	1459,
	1463,
	1469,
	1477,
	1485,
	1491,
	1498,
	1503,
	1508,
	1517,
	1526,
	1536,
	1546,
	1550,
	1557,
	1563,
	1571,
	1580,
	1586,
	1599,
	1608,
	1615,
	1623,
	1628,
	1635,
	1642,
	1656,
	1661,
	1666,
	1677,
	1686,
	1689,
	1696,
	1702,
	1712,
	1722,
	1731,
	1738,
	1741,
	1749,
	1759,
	1769,
	1775,
	1783,
	1791,
	1800,
	1810,
	1817,
	1823,
	1829,
	1837,
	1843,
	1855,
	1862,
	1876,
	1884,
	1888,
	1896,
	1906,
	1915,
	1920,
	1930,
	1938,
	1941,
	1951,
	1959,
	1964,
	1968,
	1983,
	1988,
	1994,
	2003,
	2009,
	2014,
	2022,
	2030,
	2040,
	2046,
	2052,
	2057,
	2062,
	2068,
	2073,
	2079,
	2086,
	2091,
	2098,
	2103,
	2109,
	2119,
	2134,
	2143,
	2148,
	2155,
	2162,
	2167,
	2176,
	2185,
	2190,
	2203,
	2211,
	2217,
	2230,
	2239,
	2248,
	2259,
	2269,
	2280,
	2287,
	2293,
	2300,
	2304,
	2313,
	2320,
	2329,
	2333,
	2338,
	2347,
	2354,
	2360,
	2365,
	2370,
	2376,
	2385,
	2393,
	2399,
	2403,
	2408,
	2412,
	2416,
	2421,
	2426,
	2429,
	2434,
	2444,
	2455,
	2459,
	2467,
	2474,
	2482,
	2486,
	2493,
	2498,
	2505,
	2511,
	2519,
	2528,
	2535,
	2538,
	2542,
	2549,
	2554,
	2558,
	2561,
	2566,
	2571,
	2580,
	2589,
	2596,
	2604,
	2607,
	2613,
	2624,
	2631,
	2635,
	2641,
	2646,
	2655,
	2663,
	2674,
	2680,
	2686,
	2696,
	2705,
	2712,
	2720,
	2730,
	2741,
	2749,
	2758,
	2766,
	2772,
	2780,
	2787,
	2796,
	2806,
	2816,
	2824,
	2833,
	2842,
	2850,
	2856,
	2867,
	2878,
	2888,
	2899,
	2911,
	2919,
	2931,
	2937,
	2943,
	2949,
	2954,
	2960,
	2965,
	2974,
	2982,
	2992,
	2996,
	3007,
	3019,
	3027,
	3034,
	3042,
	3051,
	3059,
	3066,
	3073,
	3080,
	3091,
	3099,
	3107,
	3113,
	3121,
	3130,
	3137,
	3147,
	3155,
	3162,
	3168,
	3174,
	3179,
	3188,
	3195,
	3203,
	3212,
	3216,
	3227,
	3232,
	3237,
	3247,
	3254,
	3262,
	3269,
	3276,
	3283,
	3292,
	3299,
	3306,
	3316,
	3325,
	3335,
	3348,
	3355,
	3363,
	3376,
	3380,
	3386,
	3391,
	3397,
	3404,
	3409,
	3416,
	3424,
	3431,
	3436,
	3445,
	3454,
	3459,
	3467,
	3471,
	3486,
	3504,
	3514,
	3534,
	3547,
	3564,
	3577,
	3586,
	3593,
	3604,
	3610,
	3620,
	3631,
	3649,
	3666,
	3685,
	3692,
	3696,
	3703,
	3709,
	3716,
	3724,
	3731,
	3738,
	3744,
	3757,
	3771,
	3784,
	3791,
	3801,
	3809,
	3819,
	3825,
	3832,
	3844,
	3850,
	3857,
	3869,
	3880,
	3885,
	3894,
	3904,
	3914,
	3919,
	3924,
	3929,
	3934,
	3939,
	3949,
	3962,
	3976,
	3985,
	3993,
	4002,
	4005,
	4014,
	4026,
	4036,
	4042,
	4050,
	4059,
	4064,
	4069,
	4078,
	4086,
	4091,
	4097,
	4105,
	4115,
	4127,
	4137,
	4149,
	4157,
	4163,
	4170,
	4178,
	4187,
	4194,
	4203,
	4212,
	4218,
	4225,
	4229,
	4234,
	4240,
	4249,
	4258,
	4272,
	4279,
	4285,
	4294,
	4304,
	4310,
	4317,
	4327,
	4335,
	4345,
	4354,
	4362,
	4370,
	4378,
	4383,
	4389,
	4397,
	4405,
	4414,
	4423,
	4428,
	4434,
	4440,
	4451,
	4458,
	4463,
	4470,
	4478,
	4483,
	4491,
	4497,
	4501,
	4515,
	4525,
	4536,
	4546,
	4556,
	4570,
	4579,
	4585,
	4593,
	4606,
	4615,
	4619,
	4624,
	4628,
	4637,
};

#define MYSSCANKEYWORDS_NUM_KEYWORDS 586

static int
MysScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1174] = {
		447,   343,   32767, 0,     242,   -283,  32767, 32767,
		514,   502,   287,   274,   32767, 346,   32767, 32767,
		32767, -78,   32767, 32767, 227,   32767, 0,     32767,
		0,     18,    692,   0,     32767, 32767, 34,    -415,
		-447,  307,   32767, -111,  0,     128,   0,     392,
		356,   515,   94,    560,   32767, 32767, -66,   32767,
		-607,  -372,  267,   -223,  32767, -97,   -207,  32767,
		32767, 32767, 227,   838,   -208,  221,   644,   -717,
		32767, 436,   384,   780,   32767, 32767, 32767, 32767,
		32767, 376,   818,   32767, -89,   587,   0,     14,
		32767, 0,     156,   11,    32767, 211,   301,   -91,
		250,   1343,  227,   605,   0,     218,   0,     -258,
		32767, -385,  243,   32767, 0,     32767, 32767, 0,
		563,   105,   -99,   32767, 68,    32767, 508,   32767,
		0,     -125,  -386,  32767, 153,   32767, 32767, 0,
		0,     523,   32767, -200,  993,   32767, -8,    32767,
		10,    742,   32767, 106,   32767, 32767, 59,    32767,
		-906,  200,   278,   32767, 509,   -39,   425,   0,
		142,   32767, -259,  32767, 46,    155,   -47,   0,
		0,     32767, 456,   0,     -265,  32767, 0,     101,
		0,     445,   32767, 0,     32767, 104,   0,     -406,
		32767, 32767, -261,  360,   456,   32767, 147,   0,
		319,   0,     32767, 468,   58,    -203,  32767, 340,
		32767, 32767, 325,   32767, 0,     32767, 220,   224,
		0,     32767, 0,     -42,   -45,   32767, 554,   32767,
		32767, 32767, 32767, 0,     0,     1043,  17,    4,
		32767, 32767, 32767, 128,   32767, -37,   0,     32767,
		32767, 0,     734,   32767, 32767, 27,    0,     32767,
		32767, 580,   32767, 32767, 16,    102,   32767, 32767,
		209,   32767, 231,   32767, 6,     32767, 32767, 268,
		-23,   358,   314,   32767, 32767, 93,    0,     32767,
		-154,  589,   32767, 32767, 32767, 32767, 6,     629,
		477,   32767, 37,    254,   529,   1204,  278,   517,
		32767, 194,   32767, -197,  32767, 172,   0,     0,
		0,     -220,  32767, 503,   32767, 32767, -216,  32767,
		0,     351,   -380,  -70,   32767, 834,   32767, 127,
		32767, -102,  158,   164,   -294,  145,   0,     498,
		-300,  28,    214,   0,     -1145, 32767, 32767, 49,
		0,     0,     527,   32767, 0,     -162,  32767, 35,
		32767, 554,   -16,   155,   0,     393,   32767, 750,
		32767, 32767, -89,   -8,    32767, 458,   32767, 32767,
		96,    0,     32767, 32767, 494,   0,     86,    32767,
		719,   0,     408,   949,   187,   135,   31,    32767,
		32767, 11,    0,     185,   0,     32767, 32767, 32767,
		215,   0,     32767, -150,  0,     95,    -239,  345,
		32767, 327,   -733,  0,     433,   5,     32767, 37,
		32767, 34,    32767, 32767, 110,   -159,  79,    277,
		32767, 0,     167,   32767, 50,    1,     184,   542,
		32767, 532,   -448,  32767, -125,  0,     -20,   26,
		244,   32767, -23,   38,    98,    237,   230,   1,
		40,    32767, 32767, 32767, 150,   111,   521,   367,
		378,   112,   0,     -129,  0,     393,   285,   227,
		0,     468,   32767, 0,     32767, -336,  546,   0,
		-63,   264,   208,   547,   -286,  -317,  32767, 327,
		32767, 0,     -108,  0,     -21,   8,     32767, 144,
		98,    1384,  83,    174,   -112,  32767, 32767, -23,
		32767, 32767, 16,    14,    32767, 492,   -179,  181,
		-195,  0,     32767, 32767, 274,   333,   248,   32767,
		569,   -42,   60,    0,     32767, 32767, 539,   32767,
		32767, 0,     185,   0,     32767, 364,   32767, 300,
		0,     -66,   0,     746,   676,   97,    32767, 32767,
		0,     0,     0,     32767, 252,   32767, 32767, 205,
		-449,  30,    506,   216,   -285,  473,   -319,  -166,
		239,   383,   32767, 32767, -73,   582,   -70,   32767,
		0,     211,   330,   32767, 41,    704,   45,    495,
		32767, 49,    32767, 32767, 32767, 457,   29,    -7,
		32767, -159,  0,     -190,  -558,  1040,  435,   -313,
		0,     236,   32767, 12,    32767, 32767, 0,     568,
		32767, 32767, 32767, 1359,  32767, 149,   32767, 32767,
		32767, 430,   272,   523,   61,    300,   0,     -128,
		44,    -193,  -51,   32767, -297,  0,     32767, 32767,
		496,   456,   213,   425,   339,   505,   443,   32767,
		-122,  32767, 409,   733,   32767, 0,     32767, 32767,
		584,   32767, 236,   32767, 32767, 0,     32767, 353,
		887,   32767, 0,     32767, 708,   32767, 32767, 224,
		334,   347,   0,     32767, 0,     32767, 858,   0,
		237,   32767, 39,    32767, 0,     32767, 32767, 0,
		32767, 523,   208,   32767, 0,     32767, -15,   43,
		0,     578,   -285,  183,   137,   32767, 0,     32767,
		32767, 85,    11,    32767, 32767, 32767, -170,  505,
		32767, 32767, -123,  0,     494,   32767, 373,   322,
		531,   429,   32767, 32767, -262,  45,    32767, 32767,
		32767, 459,   32767, 304,   32767, 451,   32767, 7,
		32767, 155,   491,   74,    0,     100,   32767, 342,
		74,    0,     32767, 222,   32767, 32767, 580,   478,
		318,   867,   32767, 32767, -542,  336,   -516,  -332,
		32767, 32767, 0,     32767, 0,     0,     32767, 32767,
		352,   129,   326,   0,     0,     32767, 32767, 32767,
		32767, 116,   32767, 32767, 299,   32767, 296,   32767,
		42,    32767, 148,   32767, 36,    32767, 32767, 0,
		32767, 32767, 419,   32767, 528,   0,     32767, 112,
		32767, 58,    212,   486,   32767, 32767, 32767, 32767,
		32767, 32767, 32767, 579,   0,     32767, 198,   0,
		304,   255,   32767, 32767, 0,     32767, 32767, 500,
		-248,  32767, 0,     583,   32767, 231,   32767, 32767,
		32767, -400,  240,   0,     101,   325,   111,   32767,
		369,   32767, 32767, 314,   273,   32767, 32767, 478,
		363,   32767, 199,   252,   722,   0,     32767, 32767,
		32767, 0,     0,     284,   32767, -513,  32767, 262,
		32767, 32767, -394,  441,   371,   32767, 0,     159,
		0,     32767, 487,   32767, 32767, -225,  -3,    32767,
		0,     251,   661,   32767, 180,   32767, 32767, 0,
		0,     281,   32767, 650,   32767, -169,  347,   32767,
		37,    0,     0,     368,   -754,  437,   264,   194,
		0,     258,   121,   0,     32767, 32767, 32767, 32767,
		32767, -65,   32767, 58,    0,     -451,  512,   341,
		32767, -127,  0,     32767, 153,   32767, 0,     20,
		0,     32767, 260,   32767, 32767, 501,   32767, 270,
		764,   32767, 219,   32767, 32767, 2,     332,   77,
		204,   557,   0,     355,   32767, -293,  -92,   39,
		0,     1148,  32767, 32767, 32767, 0,     477,   32767,
		202,   -131,  0,     0,     32767, 32767, 223,   32767,
		0,     480,   -348,  32767, 0,     32767, 0,     525,
		32767, 10,    32767, 32767, -26,   32767, 32767, 546,
		361,   -103,  32767, 554,   0,     -425,  32767, 382,
		32767, 32767, -556,  -108,  32767, 32767, 281,   32767,
		336,   0,     550,   941,   32767, 0,     741,   550,
		-716,  197,   368,   0,     32767, 443,   32767, 32767,
		654,   32767, 0,     -445,  104,   0,     32767, 452,
		574,   138,   8,     1104,  32767, 72,    321,   42,
		32767, 0,     32767, 32767, 32767, 123,   0,     32767,
		0,     159,   32767, 25,    32767, 32767, 547,   0,
		32767, 0,     169,   32767, 0,     294,   133,   32767,
		-160,  32767, 32767, 32767, 0,     292,   -387,  32767,
		189,   79,    675,   32767, 32767, 32767, 132,   32767,
		811,   32767, 0,     32767, 32767, 330,   32767, 32767,
		0,     32767, 0,     317,   32767, 0,     469,   0,
		32767, 32767, 141,   -284,  0,     32767, 172,   395,
		0,     32767, 32767, 0,     439,   534,   32767, 32767,
		32767, 0,     32767, 0,     32767, 402,   0,     32767,
		0,     0,     273,   0,     0,     32767, -467,  252,
		163,   -307,  32767, -534,  387,   227,   0,     32767,
		32767, 32767, 298,   282,   0,     140,   537,   32767,
		32767, 0,     32767, 120,   195,   75,    0,     663,
		-268,  186,   32767, 880,   204,   32767, 854,   0,
		32767, 32767, 32767, 0,     32767, 0,     32767, 0,
		176,   473,   -467,  16,    0,     333,   0,     -277,
		-731,  9,     32767, 32767, 32767, 32767, 32767, 344,
		-164,  32767, 341,   -42,   249,   530,   32767, 326,
		0,     337,   507,   32767, 382,   32767, 32767, 83,
		-153,  511,   32767, 189,   87,    410,   0,     32767,
		424,   116,   32767, 32767, 32767, 32767, 557,   170,
		193,   808,   0,     191,   32767, 0,     107,   0,
		245,   316,   32767, 575,   320,   32767, 32767, 32767,
		297,   0,     80,    -10,   0,     -142,  32767, 383,
		32767, 504,   -264,  308,   150,   32767, 32767, 404,
		93,    0,     0,     107,   715,   32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 17 + c;
	}
	return h[a % 1174] + h[b % 1174];
}

const ScanKeywordList MysScanKeywords = {
	MysScanKeywords_kw_string,
	MysScanKeywords_kw_offsets,
	MysScanKeywords_hash_func,
	MYSSCANKEYWORDS_NUM_KEYWORDS,
	19
};

#endif							/* MYS_KWLIST_D_H */
